package jrising.myapplication.Cookbooks


import android.os.Bundle
import android.support.v4.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup

import jrising.myapplication.R


/**
 * A [Fragment] subclass used to display a user's cookbooks, or a curator's cookbook
 * Use the [CookbookFragment.newInstance] factory method to
 * create an instance of this fragment.
 *
 */
class CookbookFragment : Fragment() {
    // TODO: Rename and change types of parameters
    private var param1: String? = null
    private var param2: String? = null

    /**
     * Autogenerated function called to create the view during the [Fragment] lifetime
     */
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        arguments?.let {

        }
    }

    /**
     * Autogenerated function called after the view is created in the [Fragment] lifetime
     */
    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_cook_book, container, false)
    }


    companion object {
        /**
         * Use this factory method to create a new instance of
         * this fragment using the provided parameters.
         *
         * @param param1 Parameter 1.
         * @param param2 Parameter 2.
         * @return A new instance of fragment CookBookFragment.
         */
        // TODO: Rename and change types and number of parameters
        @JvmStatic
        fun newInstance(param1: String, param2: String) =
            CookbookFragment().apply {
                arguments = Bundle().apply {

                }
            }
    }
}
