# Stages of pipeline, should match with stage tag inside each job.
# Each stages executes in sequence, if previous job fails, then all the preceeding jobs are skipped.
stages:
  - mavenbuild
  - maventest
  - autodeploy
  - androidbuild
  - androidtest

# tags: "shell" should match with the tag name provided to runner, for spring runner should execute in shell.
# Notice that in petclinic project, the spring project is in root of master, if yours is in folder then cd to that folder.
maven-build:
  stage: mavenbuild
  only:
    refs:
      - master
  tags:
    - spring_tag
  script:
    # - cd /home/public/project/team_27/Backend/initial
    ## - sudo git pull 
    ## - git merge origin/initial master
    # - mvn clean install -B -X
    - cd Backend/initial
    - mvn package -B
  
# artifacts are created when job executes successfully, and can be manually downloaded from GitLab GUI.
# artifacts are not mandatory, buts it good practice, in case auto deploy fails, you can manually download the jar.
maven-test:
  stage: maventest
  only:
    refs:
      - master
  tags:
    - spring_tag
  script:
    # - cd /home/public/project/team_27/Backend/initial
    # - mvn test 
    - cd Backend/initial
    - mvn test
  artifacts:
    paths:
      ## - /home/public/target/*.jar
      # - /home/public/project/team_27/Backend/initial/target/*.jar
      - initial/target/*.jar
  
# Below stage builds, deploys and executes the jar as service.
# Make sure there is /target directory in your server, else script will fail, or use any other folder you like.
# If you are changing the folder, reflect the change in systemd-web-demo service too.
autoDeploy:
  stage: autodeploy
  only:
    refs:
      - master
  tags: 
   - spring_tag
  script:
    # - cd /home/public/project/team_27/Backend/initial
    # - mvn clean install
    ## - mvn package
    # - sudo mv target/*.jar /home/public/target/gs-spring-boot-0.1.0.jar
    ## - cd ../../../../..
    ## - sudo mv public/project/team_27/Backend/initial/target/gs-spring-boot-0.1.0.jar public/target/gs-spring-boot-0.1.0.jar
    # - sudo systemctl stop system-kitchen
    # - sudo systemctl start system-kitchen
    - cd Backend/initial
    - mvn package
    - sudo mv target/*.jar /home/public/target/gs-spring-boot-0.1.0.jar
    - sudo systemctl stop system-kitchen
    - sudo systemctl start system-kitchen

    
# To build android projects
# Notice that we cd into Android_test folder which contains all Android files before building apk.    
# Ensure the tag matches with the tag created for Android runner
# Android runner should have docker as executor.
android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  only:
    refs:
      - master
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - cd Frontend/Home_
    - chmod +x ./gradlew
  tags:
    - android_tag
  script:
    - ./gradlew assemble
  artifacts:
    paths:
    - Home_/app/build/outputs/
  
android-tests:
  image: javiersantos/android-ci:latest
  stage: androidtest
  only:
    refs:
      - master
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - cd Frontend/Home_
    - chmod +x ./gradlew
  tags:
    - android_tag
  script:
    - ./gradlew test
