package jrising.myapplication.RecipeComments

import android.os.Bundle
import android.support.v4.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import com.android.volley.*
import com.android.volley.toolbox.JsonArrayRequest
import com.android.volley.toolbox.JsonObjectRequest
import jrising.myapplication.R
import jrising.myapplication.app.AppController
import jrising.myapplication.net_utils.Const
import jrising.myapplication.net_utils.Userinfo
import jrising.myapplication.net_utils.VolleyController
import org.json.JSONArray
import org.json.JSONObject

import kotlinx.android.synthetic.main.fragment_view_recipe_comments.*

// the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
private const val ARG_PARAM1 = "ID"

/**
 * A [Fragment] subclass used to display comments for a recipe

 * Use the [ViewRecipeFragment.newInstance] factory method to
 * create an instance of this fragment.
 *
 */
class ViewRecipeCommentsFragment : Fragment() {
    /**
     * The [String] RecipeID for the fragment
     */
    private var ID: String? = null
    /**
     * The [IRecipeCommentHandler] to handle comments for this fragment
     */
    var commentHandler : IRecipeCommentHandler = BasicRecipeCommmentHandler()

    /**
     * Generated override method generated by Android Studio
     * Will try to load the recipeID from the saved state bundle, if it exists
     */
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        arguments?.let {
            ID = it.getString(ARG_PARAM1)
        }
    }

    /**
     * A method to initialize the fragment with the given RecipeID
     * @param id The [String] RecipeID for the fragment
     */
    fun init(id : String?) {
        ID = id
    }

    /**
     * Generated override method generated by Android Studio
     */
    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        val view : View = inflater.inflate(R.layout.fragment_view_recipe_comments, container, false)
        return view
    }

    /**
     * Generated override method generated by Android Studio which runs when the [Fragment] has the view created
     * Attaches onClickListeners for the post comment and refresh buttons, and then refreshes the comments
     */
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        val ID = ID ?: return
        rview_comment_post.setOnClickListener{
            onPostButtonPressed()
        }
        rcomment_refresh.setOnClickListener {
            RefreshComments(ID)
        }
        RefreshComments(ID)
    }

    private fun onPostButtonPressed() {
        val view = view ?: return
        val ID = ID ?: return
        val input = input_comment_content.text.toString()
        commentHandler.postComment(ID, input, view)
    }

    private fun RefreshComments(recipeID : String) {
        val view = view ?: return
        removeFragments()
        commentHandler.refreshComments(recipeID, view)
    }

    private fun removeFragments() {
        val fragmentManager = childFragmentManager
        val fragments = fragmentManager.fragments
        val transaction = fragmentManager.beginTransaction()

        fragments.forEach{
            transaction.remove(it)
        }

        transaction.commit()
    }

    companion object {
        /**
         * Use this factory method to create a new instance of
         * this fragment using the provided parameters.
         *
         * @param param1 Parameter 1.
         * @param param2 Parameter 2.
         * @return A new instance of fragment ViewRecipeFragment.
         */
        // TODO: Rename and change types and number of parameters
        @JvmStatic
        fun newInstance(param1: String, param2: String) =
            ViewRecipeCommentsFragment().apply {
                arguments = Bundle().apply {
                    putString(ARG_PARAM1, param1)
                }
            }
    }
}
